"""remove_service_table_fixed

Revision ID: 7ebadd743a0e
Revises: c8aebbcf8130
Create Date: 2025-12-15 18:02:34.196983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebadd743a0e'
down_revision: Union[str, Sequence[str], None] = 'c8aebbcf8130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
